version: "3.8"

services:
    gh-runner:
        container_name: gh-runner
        restart: always
        image: bobcorp-github-runner:latest
        build:
            context: .
            args:
                RUNNER_VERSION: "2.311.0"
        env_file:
            - .env
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock
            - /var/run/docker.sock:/var/run/docker.sock
        user: "1001:0"
